name: Sync to S3

on:
  push:
    branches: [ main ]  # Update for desired branch(es)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1  # Replace with your desired region
      - name: Upload content to S3
        run: aws s3 cp --recursive website_content --region us-east-1 s3://alvinlywebsite
